### ISSUE TITLE
发现结果里有些地址的RDI标记是Commercial

### ISSUE THREAD

**Issue by largepuma** [starccy/atmb-us-non-cmra#1]
举例：Lumberton,156 S Main St,Lumberton,TX,77657,US$9.99/month,https://www.anytimemailbox.com/s/lumberton-95b-w-chance-road,Residential,N

在smarty里的查询就是commercial
![status](https://github.com/starccy/atmb-us-non-cmra/assets/395614/57531b1a-00e0-4ab7-b6cd-1b0e735cee18)

**Comment by starccy** [comment]
感谢反馈。我发现是门牌号的问题。目前查询没有使用具体的门牌号，我加一下。
