### ISSUE TITLE
大佬，请教下怎么设置环境变量

### ISSUE THREAD

**Issue by huzisir** [starccy/atmb-us-non-cmra#3]
我是在系统高级设置里系统变量新建了一个变量名CREDENTIALS，值就输的实际Auth ID1=Auth Token1，Auth ID2=Auth Token2，但运行最后提示environment variable must be set: NotPresent，估计设置环境变量错了，求教，万分感谢

**Comment by starccy** [comment]
可以直接在终端里设置。如果你用的 cmd，先执行：

```bat
set CREDENTIALS=ID1=Token1,ID2=Token2
```

再执行程序的运行命令

**Comment by huzisir** [comment]
感谢大佬，后来我还是在系统高级设置里设置的，不过是在系统变量上面的用户变量里新建的，摸索了一阵也算成功运行了
