### ISSUE TITLE
还有这个错误

### ISSUE THREAD

**Issue by huzisir** [starccy/atmb-us-non-cmra#4]
[2024-08-21T07:41:17Z ERROR atmb_us_physical] Error: Some mailbox's detail cannot be fetched
error: process didn't exit successfully: `target\release\atmb-us-physical.exe` (exit code: 1)

**Comment by starccy** [comment]
看起来是某些地址的格式发生了变化，我晚些时候看下

**Comment by huzisir** [comment]
这应该是偶然性的问题，后来就是试了直接双击atmb-us-physical.exe运行，到筛选地址时闪退，又通过终端多运行尝试了几次也成功了
