### ISSUE TITLE
大佬，发现几个问题

### ISSUE THREAD

**Issue by huzisir** [starccy/atmb-us-non-cmra#5]
短时间内两次筛选的结果不一致，昨晚筛选了一次结果是361个地址，今天上午又运行了一次，筛选出150多个地址，偏差有点大，而且像加州的地址一个都没有，我有点不信，加州300多个地址不可能都是商业地址啊，望大佬优化下，感激不尽

**Comment by huzisir** [comment]
这是不是因为smarty账号的限制，代码运行两次就把2000次数用完了，第三次运行结果就不准了，现在运行完生成的是空的excel文件

**Comment by starccy** [comment]
是这样的，目前 smarty 那边没有获取 API 使用量的接口，程序假设是每个账号都是 1000 条余量。如果要多次执行需要用新的 token. 建议用一些线上临时邮箱来注册账号。
