### ISSUE TITLE
大佬，这个问题又出现了，能优化吗

### ISSUE THREAD

**Issue by huzisir** [starccy/atmb-us-non-cmra#6]
[2024-08-21T07:41:17Z ERROR atmb_us_physical] Error: Some mailbox's detail cannot be fetched
error: process didn't exit successfully: target\release\atmb-us-physical.exe (exit code: 1)

**Comment by starccy** [comment]
好的，我这两天排查一下

**Comment by starccy** [comment]
不好意思，最近才有时间。现在我添加了重试次数。最新的 csv 也同步到项目里了。

**Comment by huzisir** [comment]
大佬威武，现在不知道是不是smarty一个账号限制1000次查询次数了，我smarty账号用脚本查过一次后，下个月再用脚本查询，查到后面就好多error，所以旧脚本我都是又用新注册smarty账号来查的，csv就不是空文件，不知道大佬是不是解决的这个问题

**Comment by starccy** [comment]
@huzisir 这次更新是避免网络波动中途报错获取不到结果的问题。你说的这个问题我怀疑是账号 API 次数耗尽后系统没有自动重置。
可惜 smarty 的 API 不提供查询剩余使用量的方法。可以手动去 https://www.smarty.com/account/subscriptions 看下 API 的使用状态。
我建议可以找一些提供临时邮箱的网站，随用随注册，用完就扔，变向绕过 API 次数的限制。
